version: 2.1
jobs:
  hello_World:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
        name: make it work
        command: |
          echo "hello world" >> ~/hello
      - persist_to_workspace:
          root: ~/
          paths:
            - hello

  say_Hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo $MY_NAME
      - attach_workspace:
          at: ~/
      - run: cat ~/hello

workflows:
  new_workflow:
    jobs:
      - hello_World
      - say_Hello:
          requires:
            - hello_World
